WITH TRIPS as (

select
RIDE_ID,
RIDEABLE_TYPE,
TO_TIMESTAMP(STARTED_AT) AS TRIP_DATE,
START_STATION_ID AS START_STATION_ID,
END_STATION_ID AS END_STATION_ID,
MEMBER_CASUAL as MEMBER_CASUAL,
DATEDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS,

from {{ source('demo', 'bike') }}
where RIDE_ID != 'ride_id'

limit 10

)

select * from TRIPS